# Dockerfile for Go Backend

# Step 1: Build the Go application in the same container
FROM golang:1.20 AS build

# Set the working directory
WORKDIR /app

# Copy the go mod files
COPY go.mod go.sum ./

# Download the Go dependencies
RUN go mod tidy

# Copy the rest of the application
COPY . .

# Build the Go application
RUN go build -o /app/goauth

# Step 2: Run the application in the same container (no need to copy to another container)
EXPOSE 8000

# Run the Go backend application
CMD ["/app/goauth"]
